name: UBA_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'          
      - name: build docker image
        run:  docker build -t cp4i:v1 -f dockerfile .
      - name: Login with OCR
        run: docker login -u admin -p $(oc whoami -t) http://default-route-openshift-image-registry.cp4intpg-wdc04-7upm3s-8946bbc006b7c6eb0829d088919818bb-0000.us-east.containers.appdomain.cloud
      - name: docker tag
        run:  docker tag cp4i:v1 default-route-openshift-image-registry.cp4intpg-wdc04-7upm3s-8946bbc006b7c6eb0829d088919818bb-0000.us-east.containers.appdomain.cloud/cp4i/cp4i:v1
      - name: docker push to OC internal reqistry
        run:  docker push default-route-openshift-image-registry.cp4intpg-wdc04-7upm3s-8946bbc006b7c6eb0829d088919818bb-0000.us-east.containers.appdomain.cloud/cp4i/cp4i:v1
      - name: oc login
        run: |
             cd /usr/local/bin/ 
             ./oc login --token=sha256~T39HWWa_kpPye_dotijhM_AAZKGKUvHyZ1BDaSpO940 --server=https://c104-e.us-east.containers.cloud.ibm.com:31739
             ./oc project cp4i
             ./oc create -f /home/bandaru/Desktop/docker/docker/cp4inew/cp4i.yaml
    
