name: EDB_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
 BAR_CREATION: /opt/ace-11.0.0.7/tools/mqsicreatebar
 BAR_STORE: /home/bandaru/Templates
 OCR_USERNAME: ${{secrets.OCR_USERNAME}}
 DEFAULT_ROUTE: ${{secrets.DEFAULT_ROUTE}}
 OC_TOKEN: ${{secrets.OC_TOKEN}}
 OC_SERVER: ${{secrets.OC_SERVER}}
 oc_USERNAME: ${{secrets.oc_USERNAME}}
 oc_PASSWORD: ${{secrets.oc_PASSWORD}}
 oc_login: ${{secrets.oc_login}}
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Building bar file
        run: $BAR_CREATION -data /root -b $BAR_STORE/Rest_Api_Application_Put_Get.bar -a Rest_Api_Application_Put_Get
        
      - name: Building Docker Image,Tag & Pushing to OCR Internal Registry
        run: | 
              docker build -t cp4i:v2 -f dockerfile .
              docker tag cp4i:v11 $DEFAULT_ROUTE/cp4i/cp4i:v2
              docker login -u admin -p $(oc whoami -t) http://default-route-openshift-image-registry.cp4intpg-wdc04-7upm3s-8946bbc006b7c6eb0829d088919818bb-0000.us-east.containers.appdomain.cloud
              docker push $DEFAULT_ROUTE/cp4i/cp4i:v2
      - name: oc login
        run: |
             cd /usr/local/bin/ 
             ./oc login $OC_SERVER -u $oc_USERNAME -p $oc_PASSWORD
             ./oc project cp4i 
             ./oc apply -f  /root/Rest_Api_Application_Put_Get/cp4i.yaml
             ./oc apply -f  /root/Rest_Api_Application_Put_Get/cp4i1.yaml
